### ISSUE TITLE
Which SMPL models to donwload?

### ISSUE THREAD

**Issue by sarihl** [Dolorousrtur/HOOD#11]
Hi, 
The README file links to the SMPLX download page, although the code (and paper) reference the SMPL model.
Either way, each project has many models, could you be so kind to provide a direct download link or more detailed instructions?

thank you :)

**Comment by Dolorousrtur** [comment]
HOOD uses SMPL model, not SMPLx. You can download version 1.1.0 from this website: [https://smpl.is.tue.mpg.de/](https://smpl.is.tue.mpg.de/resetpw.php?confirmlink=DaCBXaxQuE3zLQpwmxwO)

It is my fault, sorry -- I mistakenly put the link to the SMPLx website instead of the SMPL one.
