### ISSUE TITLE
Shoulders position

### ISSUE THREAD

**Issue by JPPPPPF** [Dolorousrtur/HOOD#13]
Hello!
Thank you for this awesome work on the project

However, I have a small question if u can help me out
I'm inferring hood over a specific sequence of body poses and it is in T pose (this is what the `.obj` file looks like after extracting it from the `.pkl` input file used)
![image](https://github.com/Dolorousrtur/HOOD/assets/140636770/68667285-6c9e-4f1b-b2b7-2d73910742a7)
When I run hood on this avatar, on the tshirt garment for example, the shoulders change as can be seen in the below image

![image (2)](https://github.com/Dolorousrtur/HOOD/assets/140636770/ce10bbbb-2c7c-47e8-8166-042a1557f458)

why does this happen and how can i fix it? Thank youu!

**Comment by Cao-Cong0** [comment]
I get the same error, how did you solve it?

**Comment by Cao-Cong0** [comment]
> I get the same error, how did you solve it?

ok I got it, just set config_dict['separate_arms'] = False
