### ISSUE TITLE
AttributeError: 'Inspector' object has no attribute 'inspect'

### ISSUE THREAD

**Issue by Amna-Elsaqa** [Dolorousrtur/HOOD#18]
Hello all

While trying to run the model using the provided notebook, I faced this error in the "create validation config and create `Runner` object" cell: 

![Screenshot from 2024-03-09 12-21-11](https://github.com/Dolorousrtur/HOOD/assets/76980514/8a2a98ca-4748-4e2e-bbd1-62b3cf3d2208)

And it also gives me the same AttributeError related to the keys attribute in addition to the inspect attribute used here:

![Screenshot from 2024-03-09 12-22-52](https://github.com/Dolorousrtur/HOOD/assets/76980514/9c6398da-67b0-4ecd-b0d3-96470442a459)

Has anyone faced this issue and was able to fix it? I'd really appreciate your help.
Thank you.

**Comment by JPPPPPF** [comment]
@Amna-Elsaqa hello, were u able to solve it?

**Comment by ZhenhuiL1n** [comment]
I also encountered the issue, solved it by changing the torch_geometric from 2.5 to 2.3.0
