### ISSUE TITLE
Texture of garments

### ISSUE THREAD

**Issue by seungjun-moon** [Dolorousrtur/HOOD#9]
First, thank you for providing an amazing garment model with remarkable performances.

In your paper, I saw that HOOD can reflect real-world clothes using 3D scan data (Figure 9)

Can I know how can I apply the texture to the garment mesh?

Thank you!

**Comment by Dolorousrtur** [comment]
Hi! I use [aitviewer](https://github.com/eth-ait/aitviewer) for visualization. You may want to check the docs for their [Meshes](https://github.com/eth-ait/aitviewer/blob/main/aitviewer/renderables/meshes.py) class to see different ways how can you change the appearance of the mesh (see `vertex_colors`, `face_colors`, `uv_coords` and `path_to_texture` arguments)
